# config/cucumber.yml
##YAML Template
---
android: PLATFORM=android -r features/support -r features/android -r features/steps -r features/android/pages


ios: PLATFORM=ios APP_BUNDLE_PATH=prebuilt/DG2App-cal.app  -r features/support -r features/ios/support -r features/ios/helpers -r features/steps -r features/ios/pages
